routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/





Route::get('/', 'DashboardController@index')->middleware('auth')->name('dashboard');
Route::get('/profile', function () { return view('profile.profile');})->name('profile');



/*--------------------------------------------------------------------------
| Route per: Autoret, Kategorite, Studentet, Librat, Huazimet , Arkivat 
|-------------------------------------------------------------------------*/
Route::resource('authors','AuthorController')->middleware('auth');
Route::resource('categories','CategoryController')->middleware('auth');
Route::resource('students','StudentController')->middleware('auth');
Route::resource('books','BookController')->middleware('auth');
Route::resource('borrows','BorrowController')->middleware('auth');
Route::get('arkivat','BorrowController@archive')->name('archive.index')->middleware('auth');
Route::post('borrows/active/{id}/{type}','BorrowController@active')->name('borrows.active')->middleware('auth');
Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/register', 'DashboardController@index')->middleware('auth');
Route::get('edit/user', 'UserController@edit')->name('user.edit');
Route::post('update/user', 'UserController@update')->name('user.update');

Route::get('/xxx' , function(){

	echo bcrypt('12345678');
});

resources/views/kategorite/edito.blade.php
@extends('layouts.admin')
@section('pageTitle', 'Ndrysho Kategorine')

@section('content')
<div class="row justify-content-center">
  <div class="col-lg-6">
    <div class="card card-border-color card-border-color-primary">
      <div class="card-header card-header-divider">Edito Kategori</div>
      <div class="card-body">



        <form action="{{route('categories.update', $category->id)}}" method="POST">
         @csrf 
         @method('PATCH')
         <div class="form-group pt-2">
            <label for="inputEmail">Emri</label>
            <input class="form-control" name="name" id="name" type="text" placeholder="" value="{{$category->name}}">
          </div>
          <div class="row pt-3">
            <div class="col-sm-12">
                <button class="btn btn-space btn-primary text-uppercase" type="submit">Edito</button>
                
            </div>
          </div>
        </form> 

        
          <form action="{{route('categories.show', $category->id)}}" method="Get">
          @csrf
          <button class="btn btn-space btn-secondary text-uppercase" type="cancel">Anulo</button>
            </form>


      </div>
    </div>
  </div>
</div>
@endsection

@section('custom_footer')
    <script src="/lib/bs-custom-file-input/bs-custom-file-input.js" type="text/javascript"></script>
    <script src="/js/app-form-elements.js" type="text/javascript"></script>
@endsection
@section('custom_scripts')
 <script type="text/javascript">
  $(document).ready(function(){
    //-initialize the javascript
    App.init();
    App.formElements();
  });
</script>
@endsection

resources/views/kategorite/kategorite.blade.php
@extends('layouts.admin')
@section('pageTitle', 'Kategorite')

@section('content')
<div class="row">
  <div class="col-sm-12">
    <div class="card card-table">
      <div class="card-header">Kategorite</div>
      <div class="card-body">
        <table class="table table-striped table-hover table-fw-widget" id="table1">
          
          <thead>
            <tr>
              <th>Nr</th>
              <th>Emri</th>
              <th>Veprime</th>
            </tr>
          </thead>
          <tbody>
            @foreach($categories as $category)
            <tr class="odd gradeX">
              <td>{{$category->id}}</td>
              <td>{{$category->name}}</td>
              <td>
                <a href="{{route('categories.edit', $category->id)}}" class="btn mr-2 btn-info">Edito</a>
                
                <form action="{{route('categories.destroy', $category->id)}}" method="POST" class="w-100 d-inline">
                  @csrf
                  @method('Delete')
                <button type="submit" class="btn mr-2 btn-danger">Fshije</button>
                </form>
      
              </td>
            </tr>
            @endforeach

         
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

@endsection

@section('custom_footer')
  <script src="/lib/datatables/datatables.net/js/jquery.dataTables.js" type="text/javascript"></script>
  <script src="/lib/datatables/datatables.net-bs4/js/dataTables.bootstrap4.js" type="text/javascript"></script>
  <script src="/lib/datatables/datatables.net-buttons/js/dataTables.buttons.min.js" type="text/javascript"></script>
  <script src="/lib/datatables/datatables.net-buttons/js/buttons.flash.min.js" type="text/javascript"></script>
  <script src="/lib/datatables/jszip/jszip.min.js" type="text/javascript"></script>
  <script src="/lib/datatables/pdfmake/pdfmake.min.js" type="text/javascript"></script>
  <script src="/lib/datatables/pdfmake/vfs_fonts.js" type="text/javascript"></script>
  <script src="/lib/datatables/datatables.net-buttons/js/buttons.colVis.min.js" type="text/javascript"></script>
  <script src="/lib/datatables/datatables.net-buttons/js/buttons.print.min.js" type="text/javascript"></script>
  <script src="/lib/datatables/datatables.net-buttons/js/buttons.html5.min.js" type="text/javascript"></script>
  <script src="/lib/datatables/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js" type="text/javascript"></script>
  <script src="/lib/datatables/datatables.net-responsive/js/dataTables.responsive.min.js" type="text/javascript"></script>
  <script src="/lib/datatables/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js" type="text/javascript"></script>
  <script src="/js/app-tables-datatables.js" type="text/javascript"></script>
@endsection
@section('custom_scripts')
<script type="text/javascript">
  $(document).ready(function(){
    //-initialize the javascript
    App.init();
    App.dataTables();

    
    
  });
</script>
@endsection

resources/views/kategorite/shto.blade.php
@extends('layouts.admin')
@section('pageTitle', 'Shto Kategorite')

@section('content')
<div class="row justify-content-center">
  <div class="col-lg-6">
    <div class="card card-border-color card-border-color-primary">
      <div class="card-header card-header-divider">Shto Kategori</div>
      <div class="card-body">



        <form action="{{route('categories.store')}}" method="POST">
          <div class="form-group pt-2">
            <label for="inputEmail">Emri</label>
            <input class="form-control" name="name" id="name" type="text" placeholder="">
          </div>
          <div class="row pt-3">
            <div class="col-sm-12">
                <button class="btn btn-space btn-primary text-uppercase" type="submit">Shto</button>
                <button class="btn btn-space btn-secondary text-uppercase">Anulo</button>
            </div>
          </div>
          @csrf
        </form>



      </div>
    </div>
  </div>
</div>
@endsection

@section('custom_footer')
    <script src="/lib/bs-custom-file-input/bs-custom-file-input.js" type="text/javascript"></script>
    <script src="/js/app-form-elements.js" type="text/javascript"></script>
@endsection
@section('custom_scripts')
 <script type="text/javascript">
  $(document).ready(function(){
    //-initialize the javascript
    App.init();
    App.formElements();
  });
</script>
@endsection