routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/





Route::get('/', 'DashboardController@index')->middleware('auth')->name('dashboard');
Route::get('/profile', function () { return view('profile.profile');})->name('profile');



/*--------------------------------------------------------------------------
| Route per: Autoret, Kategorite, Studentet, Librat, Huazimet , Arkivat 
|-------------------------------------------------------------------------*/
Route::resource('authors','AuthorController')->middleware('auth');
Route::resource('categories','CategoryController')->middleware('auth');
Route::resource('students','StudentController')->middleware('auth');
Route::resource('books','BookController')->middleware('auth');
Route::resource('borrows','BorrowController')->middleware('auth');
Route::get('arkivat','BorrowController@archive')->name('archive.index')->middleware('auth');
Route::post('borrows/active/{id}/{type}','BorrowController@active')->name('borrows.active')->middleware('auth');
Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/register', 'DashboardController@index')->middleware('auth');
Route::get('edit/user', 'UserController@edit')->name('user.edit');
Route::post('update/user', 'UserController@update')->name('user.update');

Route::get('/xxx' , function(){

	echo bcrypt('12345678');
});

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="author" content="Web Geneve - https://www.webgeneve.ch/">
    <title>@yield('pageTitle')</title>
    <link rel="stylesheet" type="text/css" href="/lib/perfect-scrollbar/css/perfect-scrollbar.css"/>
    <link rel="stylesheet" type="text/css" href="/lib/material-design-icons/css/material-design-iconic-font.min.css"/>
    <link rel="stylesheet" type="text/css" href="/lib/jquery.vectormap/jquery-jvectormap-1.2.2.css"/>
    <link rel="stylesheet" type="text/css" href="/lib/jqvmap/jqvmap.min.css"/>
    <link rel="stylesheet" type="text/css" href="/lib/datetimepicker/css/bootstrap-datetimepicker.min.css"/>
    <link rel="stylesheet" href="/css/app.css" type="text/css"/>
    <style>
        .be-top-header .container-fluid{
            padding: 1px !important;
        }
        .be-top-header .be-navbar-header .navbar-brand{
            background-size: 100% 100%;
            width: 84px !important;
        }
    </style>

    @yield('custom_header')
    @yield('custom_style')
  </head>
    <body>
        <div class="be-wrapper be-fixed-sidebar">
             @include('layouts.header')
             @include('layouts.sidebar')
             <div class="be-content">
                <div class="main-content container-fluid">
                    @include('layouts.notifications')
                    @yield('content')
                </div>
             </div>     
        </div>

        <script src="/lib/jquery/jquery.min.js" type="text/javascript"></script>
        <script src="/lib/perfect-scrollbar/js/perfect-scrollbar.min.js" type="text/javascript"></script>
        <script src="/lib/bootstrap/dist/js/bootstrap.bundle.min.js" type="text/javascript"></script>
        <script src="/js/app.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/jquery.flot.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/jquery.flot.pie.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/jquery.flot.time.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/jquery.flot.resize.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/plugins/jquery.flot.orderBars.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/plugins/curvedLines.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/plugins/jquery.flot.tooltip.js" type="text/javascript"></script>
        <script src="/lib/jquery.sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
        <script src="/lib/countup/countUp.min.js" type="text/javascript"></script>
        <script src="/lib/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
        <script src="/lib/jqvmap/jquery.vmap.min.js" type="text/javascript"></script>
        <script src="/lib/jqvmap/maps/jquery.vmap.world.js" type="text/javascript"></script>
        <script src="/js/app-dashboard.js" type="text/javascript"></script>
        
        @yield('custom_footer')
        @yield('custom_scripts')
  </body>
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/header.blade.php
<nav class="navbar navbar-expand fixed-top be-top-header">
  <div class="container-fluid">
    <div class="be-navbar-header">
      <a href="/"> <img src="/img/logo-xx.png" style="width: 80%"> </a>
    </div>
   {{--  <div class="page-title"><span>Dashboard</span></div> --}}
    @if(Auth::check())
    <div class="be-right-navbar">
      <ul class="nav navbar-nav float-right be-user-nav">
        <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" role="button" aria-expanded="false"><img src="/img/avatar.png" alt="Avatar"><span class="user-name">{{Auth::user()->name}}</span></a>
          <div class="dropdown-menu" role="menu">     
            <div class="user-info">
              <div class="user-name">{{Auth::user()->name}} </div>
            </div><a class="dropdown-item" href="{{route('user.edit')}}"><span class="icon mdi mdi-face"></span>Profili</a>

            <a class="dropdown-item" href="{{ url('/logout') }}"><span class="icon mdi mdi-power"></span>Logout</a>
          </div>
        </li>
      </ul>
     
    </div>
    @else
      <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            
                           {{--  @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif --}}
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
      </div>
    @endif
  </div>
</nav>

resources/views/layouts/notifications.blade.php
<div class="container">
	<div class="row">
	<div class="col-md-12">
	@if (session('status'))
		    <div class="alert alert-success text-center">
				{{session('status')}}
		    </div>
		@endif
		@if (session('error'))
		    <div class="alert alert-danger text-center">
				{{session('error')}}
		    </div>
		@endif
		@if (session('danger'))
		    <div class="alert alert-danger text-center">
				{{session('danger')}}
		    </div>
		@endif
		@if (session('warning'))
		    <div class="alert alert-warning text-center">
				{{session('warning')}}
		    </div>
		@endif
		<!-- MailChimp -->
		@if (session('status-MailChimp'))
			    <div class="alert alert-success text-center">
					{{session('status')}}
			    </div>
			@endif
			@if (session('error-MailChimp'))
			    <div class="alert alert-danger text-center">
					{{session('error')}}
			    </div>
			@endif
	  @if ($errors->any())
	    <div class="alert alert-danger text-center">
	        <ul>
	            @foreach ($errors->all() as $error)
	                <li>{{ $error }}</li>
	            @endforeach
	        </ul>
	    </div>
		@endif
	</div>
</div>
</div>

resources/views/layouts/sidebar.blade.php
<div class="be-left-sidebar">
  <div class="left-sidebar-wrapper"><a class="left-sidebar-toggle" href="/">Paneli Kryesor</a>
    <div class="left-sidebar-spacer">
      <div class="left-sidebar-scroll">
        <div class="left-sidebar-content">
          <ul class="sidebar-elements">
            <li class="divider">Menu</li>
            <li class="active"><a href="/"><i class="icon mdi mdi-home"></i><span>Paneli Kryesor</span></a></li>
            <li class="parent {{ Request::is('books*') ? 'open' : '' }}">
              <a href="{{ route('books.index') }}"><i class="icon mdi mdi-book"></i><span>Librat</span></a>
              <ul class="sub-menu">
                <li><a href="{{route('books.index')}}">Librat</a></li>
                <li><a href="{{route('books.create')}}">Shto</a></li>
              </ul>
            </li>
            <li class="parent {{ Request::is('categories*') ? 'open' : '' }}">
              <a href="{{ route('categories.index') }}"><i class="icon mdi mdi-filter-list"></i><span>Kategoritë</span></a>
              <ul class="sub-menu">
                <li><a href="{{route('categories.index')}}">Kategoritë</a></li>
                <li><a href="{{route('categories.create')}}">Shto</a></li>
              </ul>
            </li>
            <li class="parent {{ Request::is('authors*') ? 'open' : '' }}"><a href="{{ route('authors.index') }}"><i class="icon mdi mdi-accounts"></i><span>Autort</span></a>
              <ul class="sub-menu">
                <li><a href="{{route('authors.index')}}">Autort</a></li>
                <li><a href="{{route('authors.create')}}">Shto</a></li>
              </ul>
            </li>
            <li class="parent {{ Request::is('students*') ? 'open' : '' }}">
              <a href="{{ route('students.index') }}"><i class="icon mdi mdi-accounts-alt"></i><span>Nxënsat</span></a>
              <ul class="sub-menu">
                <li><a href="{{route('students.index')}}">Nxënsat</a></li>
                <li><a href="{{route('students.create')}}">Shto</a></li>
              </ul>
            </li>
             <li class="parent {{ Request::is('borrows*') ? 'open' : '' }}">
              <a href="{{ route('borrows.index') }}"><i class="icon mdi mdi-book"></i><span>Huazimet</span></a>
              <ul class="sub-menu">
                <li><a href="{{route('borrows.index')}}">Huazimet</a></li>
                <li><a href="{{route('borrows.create')}}">Shto</a></li>
                <li><a href="{{route('archive.index')}}">Arkivat</a></li>
              </ul>
            </li> 
          </ul>

          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

resources/views/layouts/user.blade.php
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="author" content="Web Geneve - https://www.webgeneve.ch/">
    <title>@yield('pageTitle')</title>
    <link rel="stylesheet" type="text/css" href="/lib/perfect-scrollbar/css/perfect-scrollbar.css"/>
    <link rel="stylesheet" type="text/css" href="/lib/material-design-icons/css/material-design-iconic-font.min.css"/>
    <link rel="stylesheet" type="text/css" href="/lib/jquery.vectormap/jquery-jvectormap-1.2.2.css"/>
    <link rel="stylesheet" type="text/css" href="/lib/jqvmap/jqvmap.min.css"/>
    <link rel="stylesheet" type="text/css" href="/lib/datetimepicker/css/bootstrap-datetimepicker.min.css"/>
    <link rel="stylesheet" href="/css/app.css" type="text/css"/>
    <style>
        .be-top-header .container-fluid{
            padding: 1px !important;
        }
        .be-top-header .be-navbar-header .navbar-brand{
            background-size: 100% 100%;
            width: 84px !important;
        }
    </style>

    @yield('custom_header')
    @yield('custom_style')
  </head>
    <body>
        <div class="be-wrapper be-fixed-sidebar">
             @include('layouts.header')
             <div class="be-content">
                <div class="main-content container-fluid">
                    @include('layouts.notifications')
                    @yield('content')
                </div>
             </div>     
        </div>

        <script src="/lib/jquery/jquery.min.js" type="text/javascript"></script>
        <script src="/lib/perfect-scrollbar/js/perfect-scrollbar.min.js" type="text/javascript"></script>
        <script src="/lib/bootstrap/dist/js/bootstrap.bundle.min.js" type="text/javascript"></script>
        <script src="/js/app.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/jquery.flot.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/jquery.flot.pie.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/jquery.flot.time.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/jquery.flot.resize.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/plugins/jquery.flot.orderBars.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/plugins/curvedLines.js" type="text/javascript"></script>
        <script src="/lib/jquery-flot/plugins/jquery.flot.tooltip.js" type="text/javascript"></script>
        <script src="/lib/jquery.sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
        <script src="/lib/countup/countUp.min.js" type="text/javascript"></script>
        <script src="/lib/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
        <script src="/lib/jqvmap/jquery.vmap.min.js" type="text/javascript"></script>
        <script src="/lib/jqvmap/maps/jquery.vmap.world.js" type="text/javascript"></script>
        <script src="/js/app-dashboard.js" type="text/javascript"></script>
        
        @yield('custom_footer')
        @yield('custom_scripts')
  </body>
</html>